### ISSUE TITLE
Tarjeta de pedido

### ISSUE THREAD

**Issue by anjelhm** [anjelhm/roundsmanApp#2]
- [x] Crear archivo TarjetaPedido.js dentro de la carpeta pedidos
El componente debe mostrar lo siguiente:

- [x] Nombre del cliente, color: '#607D8B'.
- [x] Ubicación, en este caso será la dirección del cliente, color: '#CFD8DC'.
- [x] Botón Tomar pedido con fondo negro (#000000) y texto en blanco (#FFFFFF).
- [x] Botón Ver mapa  con fondo blanco (#FFFFFF) y texto negro (#000000).
- [x] Crear un modal simple que se muestre al presionar el botón ver mapa y dentro del modal 
       agregar un botón para ocultar el modal.

**Comment by ocarrizalmartinez** [comment]
apenas lo veo

**Comment by ocarrizalmartinez** [comment]
:c

**Comment by anjelhm** [comment]
Quita la etiqueta text que dice 'Nombre:' , solo deja la que llega por props, '{ nombre }', igual en ubicación quita 'Ubicación:' solo deja '{ ubicacion }'.
`<View>
            **<Text>
              Nombre:
            </Text>**
            <Text>
              { nombre }
            </Text>
          </View>
          <View>
            **<Text>
              Ubicacion:
            </Text>**
            <Text>
              { ubicacion }
            </Text>
          </View>`

**Comment by ocarrizalmartinez** [comment]
Ok 👍

**Comment by anjelhm** [comment]
En la etiqueta Boton, las props para los colores son: fondo para el background y color para el texto, solo agregaste color para el texto, agrega fondo también.

`<Boton
            etiqueta = "Tomar pedido",
            color = "#FFFFFF"
          />`

**Comment by anjelhm** [comment]
Al view que contiene los dos botones agrégale un estilo y le pones flexDirection: 'row' y un justifyContent: 'space-around' para que acomode los botones.

**Comment by anjelhm** [comment]
y falta el modal, hay un ejemplo de modal dentro de la carpeta componentes, en el archivo NuevaSesion.js, si gustas checarlo para que te guies para hacerlo.

**Comment by anjelhm** [comment]
Te falta también agregarle estilo al texto de nombre y al de ubicación, solo le pones los colores que mencioné en las instrucciones.

**Comment by ocarrizalmartinez** [comment]
Si, ya los agregué, ya para el siguiente commit van. Sólo reviso el modal 👍
